import type { Metadata } from "next";
import { Kulim_Park } from "next/font/google";
import "./globals.css";

const kulimPark = Kulim_Park({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={kulimPark.className}>{children}</body>
    </html>
  );
}
