import type { Metadata } from "next";
import { Kulim_Park } from "next/font/google";
import "../globals.css";

const kulimPark = Kulim_Park({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// https://blog.openreplay.com/i18n-in-next-14/

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  return (
    <html lang={locale}>
      <body className={kulimPark.className}>{children}</body>
    </html>
  );
}
